[tool.poetry]
name = "litoid"
version = "0.1.0"
description = "ðŸ’¡Sequence DMX lighting ðŸ’¡"
authors = ["Tom Ritchford <tom@swirly.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
numpy = "^1.24.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
